version: '3.1'

services:

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    hostname: 'pgiot_db'
    ports:
      - '5432:5432'
#    volumes:
#      - ./data/db:/var/lib/postgresql/data

  web:
    build:
      context: ./pythonIOT
    environment:
      - DB_HOST=pgiot_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - EXT_IP=${EXT_IP}
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  app:
    build:
      context: ./Service
    environment:
      - DB_HOST=pgiot_db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - MQTT_IP=${MQTT_IP}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_LOGIN=${MQTT_LOGIN}
      - MQTT_PASS=${MQTT_PASS}
    depends_on:
      - db
      - web