# Generated by Django 3.2.5 on 2021-07-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('device', models.CharField(max_length=25, verbose_name='Устройство')),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Значение')),
            ],
        ),
    ]
