# Generated by Django 3.2.5 on 2021-07-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('device', models.CharField(max_length=25, verbose_name='Устройство')),
                ('task', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Task',
            },
        ),
        migrations.AlterModelOptions(
            name='iotdata',
            options={'verbose_name': 'IOT Data'},
        ),
    ]
